package(default_visibility = ["//visibility:public"])

cc_library(
    name = "cipv_fusion_component_lib",
    srcs = ["cipv_fusion_component.cc"],
    hdrs = ["cipv_fusion_component.h"],
    deps = [
        "//cyber",
        "//cipv_fusion_component/proto:car_state_cc_proto",
        "//cipv_fusion_component/proto:cipv_fusion_cc_proto",
    ],
)
